# Generated by Django 4.1.10 on 2023-09-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('router_name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'db_table': 'page',
            },
        ),
        migrations.AddField(
            model_name='role',
            name='pages',
            field=models.ManyToManyField(related_name='role_pages', to='users.page'),
        ),
    ]
