# Generated by Django 4.1.10 on 2023-09-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_page_role_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(related_name='user_roles', to='users.role'),
        ),
    ]
