# Generated by Django 4.1.10 on 2023-09-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_moscow_manager',
            field=models.BooleanField(default=False),
        ),
    ]
