# Generated by Django 4.1.10 on 2023-11-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_page_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_chat_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
