# Generated by Django 4.1.10 on 2023-12-06 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_verification_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='telegram_chat_id',
        ),
    ]
