# Generated by Django 4.1.2 on 2024-01-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_remove_user_telegram_chat_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="type",
            field=models.CharField(
                choices=[
                    ("client", "Client"),
                    ("admin", "Admin"),
                    ("counterparty", "Counterparty"),
                    ("manager", "Manager"),
                    ("moscow_manager", "Moscow Manager"),
                ],
                default="client",
                max_length=50,
            ),
        ),
    ]
