# Generated by Django 4.1.2 on 2024-01-19 09:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_user_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_admin",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_client",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_counterparty",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_manager",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_moscow_manager",
        ),
    ]
