# Generated by Django 4.1.2 on 2024-02-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_user_telegram_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="type",
            field=models.CharField(
                choices=[
                    ("client", "Client"),
                    ("admin", "Admin"),
                    ("counterparty", "Counterparty"),
                    ("manager", "Manager"),
                    ("moscow_manager", "Moscow Manager"),
                    ("central_asia_manager", "Central Asia Manager"),
                ],
                default="client",
                max_length=50,
            ),
        ),
    ]
