# Generated by Django 4.1.2 on 2025-05-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_verificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_turkmen',
            field=models.BooleanField(default=False),
        ),
    ]
