# Generated by Django 4.1.2 on 2025-05-05 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_is_turkmen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_turkmen',
        ),
    ]
