# Generated by Django 5.0 on 2025-08-20 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='territory',
            name='description',
        ),
    ]
