# Generated by Django 5.0 on 2025-08-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counterparty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counterparty',
            name='address',
        ),
        migrations.RemoveField(
            model_name='counterparty',
            name='email',
        ),
        migrations.RemoveField(
            model_name='counterparty',
            name='phone',
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
