# Generated by Django 4.1.10 on 2023-09-28 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('counterparty', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterrailRuApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, max_length=100, unique=True)),
                ('request_file', models.FileField(blank=True, null=True, upload_to='interrail_russian/applications/')),
                ('quantity', models.IntegerField(default=1)),
                ('date', models.DateField(blank=True, null=True)),
                ('paid_telegram', models.CharField(blank=True, max_length=100)),
                ('departure', models.CharField(blank=True, max_length=100)),
                ('departure_code', models.CharField(blank=True, max_length=100)),
                ('destination', models.CharField(blank=True, max_length=100)),
                ('destination_code', models.CharField(blank=True, max_length=100)),
                ('cargo', models.CharField(blank=True, max_length=100)),
                ('hs_code', models.CharField(blank=True, max_length=100)),
                ('etcng', models.CharField(blank=True, max_length=255)),
                ('loading_type', models.CharField(choices=[('wagon', 'Wagon'), ('container', 'Container')], default='wagon', max_length=100)),
                ('weight', models.CharField(blank=True, max_length=100)),
                ('rolling_stock_1', models.CharField(blank=True, max_length=255)),
                ('rolling_stock_2', models.CharField(blank=True, max_length=255)),
                ('conditions_of_carriage', models.CharField(blank=True, max_length=255)),
                ('agreed_rate', models.CharField(blank=True, max_length=50)),
                ('border_crossing', models.CharField(blank=True, max_length=255)),
                ('containers_or_wagons', models.TextField(default='')),
                ('period', models.CharField(blank=True, max_length=255)),
                ('shipper', models.CharField(blank=True, max_length=255)),
                ('consignee', models.CharField(blank=True, max_length=255)),
                ('departure_country', models.CharField(blank=True, max_length=255)),
                ('destination_country', models.CharField(blank=True, max_length=255)),
                ('comment', models.TextField(blank=True)),
                ('forwarder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ru_applications', to='counterparty.counterparty')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ru_applications', to=settings.AUTH_USER_MODEL)),
                ('territories', models.ManyToManyField(related_name='ru_applications', to='core.territory')),
            ],
            options={
                'verbose_name': 'MoscowApplication',
                'verbose_name_plural': 'MoscowApplications',
                'db_table': 'interrail_ru_application',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='InterrailRuCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('code_status', models.CharField(choices=[('Checking', 'Checking'), ('Used', 'Used'), ('Canceled', 'Canceled'), ('Completed', 'Completed')], default='Checking', max_length=50)),
                ('number', models.CharField(blank=True, max_length=20)),
                ('smgs_code', models.CharField(blank=True, max_length=20)),
                ('smgs_date', models.DateField(blank=True, null=True)),
                ('weight', models.CharField(blank=True, default='', max_length=100)),
                ('wagon_number', models.CharField(blank=True, default='', max_length=100)),
                ('container_number', models.CharField(blank=True, default='', max_length=100)),
                ('rate', models.FloatField(blank=True, default=0)),
                ('add_charges', models.FloatField(blank=True, default=0)),
                ('smgs_file', models.FileField(blank=True, null=True, upload_to='applications/smgs_file/')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ru_codes', to='payment_codes.interrailruapplication')),
                ('territory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ru_codes', to='core.territory')),
            ],
            options={
                'verbose_name': 'InterrailRuCode',
                'verbose_name_plural': 'InterrailRuCodes',
                'db_table': 'interrail_ru_code',
            },
        ),
    ]
