# Generated by Django 4.1.10 on 2023-09-29 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_codes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interrailruapplication',
            name='sending_type',
            field=models.CharField(blank=True, choices=[('single', 'Одиночный'), ('block_train', 'КП')], max_length=100),
        ),
    ]
