# Generated by Django 4.1.10 on 2023-09-29 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_codes', '0002_interrailruapplication_sending_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interrailruapplication',
            name='paid_telegram',
            field=models.BooleanField(default=False),
        ),
    ]
