# Generated by Django 4.1.10 on 2023-09-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_codes', '0003_alter_interrailruapplication_paid_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='interrailrucode',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
