# Generated by Django 4.1.10 on 2023-09-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_codes', '0004_interrailrucode_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='interrailruapplication',
            name='add_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='interrailruapplication',
            name='agreed_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
