# Generated by Django 4.1.10 on 2023-09-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_codes', '0005_interrailruapplication_add_charges_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interrailrucode',
            name='add_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='interrailrucode',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
