# Generated by Django 4.1.10 on 2023-09-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_codes', '0006_alter_interrailrucode_add_charges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interrailruapplication',
            name='container_type',
            field=models.CharField(blank=True, choices=[('20', '20'), ('20HC', '20HC'), ('40', '40'), ('40HC', '40HC'), ('45', '45')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='interrailruapplication',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
