# Generated by Django 4.1.10 on 2023-11-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_codes', '0007_interrailruapplication_container_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interrailruapplication',
            name='border_crossing',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='interrailruapplication',
            name='conditions_of_carriage',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='interrailruapplication',
            name='etcng',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='interrailruapplication',
            name='rolling_stock_1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='interrailruapplication',
            name='rolling_stock_2',
            field=models.TextField(blank=True),
        ),
    ]
