# Generated by Django 4.1.10 on 2023-11-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_codes', '0008_alter_interrailruapplication_border_crossing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interrailruapplication',
            name='cargo',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='interrailruapplication',
            name='consignee',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='interrailruapplication',
            name='departure',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='interrailruapplication',
            name='departure_code',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='interrailruapplication',
            name='departure_country',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='interrailruapplication',
            name='destination',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='interrailruapplication',
            name='destination_code',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='interrailruapplication',
            name='destination_country',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='interrailruapplication',
            name='hs_code',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='interrailruapplication',
            name='period',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='interrailruapplication',
            name='shipper',
            field=models.TextField(blank=True),
        ),
    ]
