# Generated by Django 4.1.2 on 2024-10-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment_codes", "0009_alter_interrailruapplication_cargo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="interrailrucode",
            name="comment",
            field=models.TextField(blank=True, default=""),
        ),
    ]
