# Generated by Django 5.0 on 2025-08-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_codes', '0010_interrailrucode_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interrailruapplication',
            name='add_charges',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='interrailruapplication',
            name='agreed_rate',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='interrailruapplication',
            name='border_crossing',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='interrailruapplication',
            name='cargo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='interrailruapplication',
            name='conditions_of_carriage',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='interrailruapplication',
            name='consignee',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='interrailruapplication',
            name='container_type',
            field=models.CharField(blank=True, choices=[('20', '20ft'), ('20HC', '20ft High Cube'), ('40', '40ft'), ('40HC', '40ft High Cube'), ('45', '45ft')], max_length=255),
        ),
        migrations.AlterField(
            model_name='interrailruapplication',
            name='departure',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='interrailruapplication',
            name='departure_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='interrailruapplication',
            name='departure_country',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='interrailruapplication',
            name='destination',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='interrailruapplication',
            name='destination_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='interrailruapplication',
            name='destination_country',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='interrailruapplication',
            name='etcng',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='interrailruapplication',
            name='hs_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='interrailruapplication',
            name='paid_telegram',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='interrailruapplication',
            name='period',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='interrailruapplication',
            name='rolling_stock_1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='interrailruapplication',
            name='rolling_stock_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='interrailruapplication',
            name='sending_type',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('block_train', 'Block Train')], max_length=100),
        ),
        migrations.AlterField(
            model_name='interrailruapplication',
            name='shipper',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='interrailruapplication',
            name='weight',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='interrailrucode',
            name='add_charges',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='interrailrucode',
            name='rate',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
