# Generated by Django 5.0 on 2025-08-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_codes', '0011_alter_interrailruapplication_add_charges_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interrailruapplication',
            name='paid_telegram',
            field=models.BooleanField(default=False),
        ),
    ]
